In [1]:
import pandas as pd

 # Reading Data

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0  101.537126         1   46          1          -1              0
1  100.146611         1   71          1           0              0
2  100.715955         0   56          1           0              1
3  100.147201         1   38          0           0              0
4  101.442280         1   64          1           1              1

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2567  100.883967         1   58          0           0              0
2568  101.220548         0   86          0           1              0
2569   99.653856         0   21          0          -1              0
2570  100.678419         0   71          1           0              1
2571  101.594531         1   40          0           1              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2572 entries, 0 to 2571
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2572 non-null   float64
 1   bodyPain       2572 non-null   int64  
 2   age            2572 non-null   int64  
 3   runnyNose      2572 non-null   int64  
 4   diffBreath     2572 non-null   int64  
 5   infectionProb  2572 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 120.6 KB


In [6]:
df['diffBreath'].value_counts()

 0    904
 1    845
-1    823
Name: diffBreath, dtype: int64

In [7]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2572.000000  2572.000000  2572.000000  2572.000000  2572.000000   
mean    100.018178     0.500389    50.359642     0.487947     0.008554   
std       1.143441     0.500097    28.521838     0.499952     0.805420   
min      98.002413     0.000000     1.000000     0.000000    -1.000000   
25%      99.044684     0.000000    26.000000     0.000000    -1.000000   
50%      99.979018     1.000000    51.000000     0.000000     0.000000   
75%     101.005940     1.000000    74.000000     1.000000     1.000000   
max     101.998556     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2572.000000  
mean        0.502333  
std         0.500092  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

## Train Test Split

In [8]:
import numpy as np


In [9]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [10]:
np.random.permutation(7)

array([5, 4, 1, 3, 6, 2, 0])

In [11]:
train, test = data_split(df, 0.2)

In [12]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1127   98.392428         1   22          0           1              0
2119  101.455847         0   16          0          -1              1
2337   99.764274         0   49          0           0              0
367   101.216548         1   13          1          -1              0
1780  101.237400         1   91          1          -1              0
...          ...       ...  ...        ...         ...            ...
802   100.409152         1   20          0          -1              1
930    99.820165         0   15          1          -1              0
829   101.929071         0   37          0           0              1
25    101.533034         0   86          0           0              0
2552   99.896541         0   84          0           0              1

[514 rows x 6 columns]

In [13]:
 train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2042  100.965070         1   56          1          -1              0
2305  101.069695         0   18          0          -1              1
2472   99.992762         1    2          0          -1              1
361    99.153701         1   60          1           0              1
2280   98.593679         1    1          0          -1              1
...          ...       ...  ...        ...         ...            ...
1638  101.941136         1   37          1           1              1
1095  100.733755         1   66          1           1              1
1130  100.444126         0   86          1           0              1
1294  100.272880         1   58          0           0              0
860    99.019591         1   63          0           0              0

[2058 rows x 6 columns]

In [14]:
X_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()
X_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()


In [15]:
Y_train = train[['infectionProb']].to_numpy().reshape(2058 ,)
Y_test = test[['infectionProb']].to_numpy().reshape(514 ,)


In [16]:
Y_train

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
 clf.predict_proba([[100, 1, 22, -1, 1]])

array([[0.48779943, 0.51220057]])

In [20]:
inputFeature = [100, 1, 22, -1, 1]
infProb = clf.predict_proba([inputFeature])[0][1]

In [21]:
infProb

0.5122005684855495

In [22]:
inputFeature = [102, 1, 22, -1, 1]
infProb = clf.predict_proba([inputFeature])[0][1]

In [23]:
infProb

0.5605058574709065